# Generated by Django 4.1.6 on 2023-02-13 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_categorys_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorys',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='products',
            name='slug',
        ),
    ]
