# Generated by Django 4.1.6 on 2023-02-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_categorys_slug_remove_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorys',
            name='slug',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.CharField(default='', max_length=150),
        ),
    ]
