# Generated by Django 4.1.6 on 2023-02-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_categorys_slug_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorys',
            name='status',
            field=models.BooleanField(default=False, help_text='0=default,1=Hidden'),
        ),
    ]
