# Generated by Django 4.1.6 on 2023-02-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_categorys_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.BooleanField(default=False, help_text='0=default,1=Hidden'),
        ),
    ]
