# Generated by Django 4.1.6 on 2023-02-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=25)),
                ('Mobile', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=250)),
            ],
        ),
    ]
