# Generated by Django 4.1.6 on 2023-03-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=25)),
                ('Mobile', models.CharField(max_length=10)),
                ('pincode', models.IntegerField(max_length=10)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
    ]
