# Generated by Django 4.1.6 on 2023-03-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
