# Generated by Django 4.1.6 on 2023-03-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_checkout_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Confirm_password',
            field=models.CharField(default='', max_length=10),
        ),
    ]
