# Generated by Django 4.1.6 on 2023-03-09 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_user_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Confirm_password',
        ),
    ]
